### ISSUE TITLE
Creating new domains

### ISSUE THREAD

**Issue by sreekar2503** [und3fined/medium-unlocker#1]
To create new domains we should just add more domains to the background and manifest file right?
![background](https://user-images.githubusercontent.com/76125823/147884513-62cd4cea-1492-4578-ba50-6b38700c3d76.PNG)
![manifest](https://user-images.githubusercontent.com/76125823/147884517-62f01dc4-0626-4178-b42f-66a64b7ff6ba.PNG)
![manifest2](https://user-images.githubusercontent.com/76125823/147884518-72bd73b3-fa78-4d60-a4ec-de0b39de7c37.PNG)

**Comment by und3fined** [comment]
> To create new domains we should just add more domains to the background and manifest file right?

With privacy policy, i'll manual added new domain to addons, no any way for config domain
