### ISSUE TITLE
Manifest file is missing or unreadable error message is shown while loading the extension.

### ISSUE THREAD

**Issue by Sunilrai486** [und3fined/medium-unlocker#18]
![image](https://user-images.githubusercontent.com/18285421/170384210-44ad11c8-62a4-4c32-9dc2-e8ea2fa1c2dd.png)

**Comment by und3fined** [comment]
@Sunilrai486 Don't use source code. Download medium-unlocker.zip in releases page (https://github.com/und3fined/medium-unlocker/releases)

**Comment by Sunilrai486** [comment]
Thanks it worked.

**Comment by Sunilrai486** [comment]
Thanks it worked.

**Comment by Sunilrai486** [comment]
Thanks it worked.
