### ISSUE TITLE
expand the url list

### ISSUE THREAD

**Issue by ChenxiangWang** [und3fined/medium-unlocker#2]
Hi, 

thanks to your great work, I can read most of the blogs freely. 
Is there a way to manually expend the hacked url list? 

Thanks!

**Comment by und3fined** [comment]
> Hi,
> 
> thanks to your great work, I can read most of the blogs freely. Is there a way to manually expend the hacked url list?
> 
> Thanks!

It's can but requiment a permission access to all website. But I don't want to ask for that permission.
