### ISSUE TITLE
Add to Chrome link isn't working

### ISSUE THREAD

**Issue by arjunn21** [und3fined/medium-unlocker#30]
Add to Chrome hyperlink shows Error 404

**Comment by und3fined** [comment]
I don't understand

**Comment by arjunn21** [comment]
I mean on the README page the hyperlink for "Get Extension For Chrome" doesn't work. It shows Error 404

**Comment by und3fined** [comment]
@arjunn21 please flow this guide https://github.com/und3fined/medium-unlocker/wiki/Install-extension-for-Chromium-(base)-browser

**Comment by arjunn21** [comment]
Thanks @und3fined! Much appreciated
