### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023.

### ISSUE THREAD

**Issue by dyzcs** [und3fined/medium-unlocker#35]
Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details.
![image](https://user-images.githubusercontent.com/40335479/212077910-42d2f88a-49cd-490b-8b0f-0c94b349ff83.png)

**Comment by und3fined** [comment]
@dyzcs thanks for report, my script patch to headers.
With new `declarativeNetRequest` API (like Safari),  maybe need new way for bypass

I'll update later.

**Comment by dyzcs** [comment]
Thank you for your reply. I am also looking forward to your update.

**Comment by JTangming** [comment]
I am also looking forward to your update. +1

**Comment by Aarekaz** [comment]
Looking forward to this

**Comment by bekinin** [comment]
+1 as latest Chrome starts blocking the extension now and it's not working

**Comment by und3fined** [comment]
> +1 as latest Chrome starts blocking the extension now and it's not working

bad news :(

**Comment by pandaeli** [comment]
there is no way around this?

**Comment by kampiamodikuesto** [comment]
same problem, extension doesn't work:(

**Comment by und3fined** [comment]
@pandaeli , @kampiamodikuesto and @overthetop please use Firefox

**Comment by overthetop** [comment]
@und3fined does that mean that Chrome won't be supported?

**Comment by und3fined** [comment]
@overthetop Currently is NO. or need use older Chrome version for support Manifest v2.

**Comment by TobySkarting** [comment]
Try this https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher

**Comment by fuuqiu** [comment]
> Try this https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher

Is there a chrome that supports the mac OS system?

**Comment by kampiamodikuesto** [comment]
> @pandaeli , @kampiamodikuesto and @overthetop please use Firefox

I get same results on firefox and i cen't bbypass medium block text. is It my problem or some one get the same result also on firefox?

**Comment by BudgieBird** [comment]
@kampiamodikuesto Check https://github.com/und3fined/medium-unlocker/issues/48
