### ISSUE TITLE
Another possible way?

### ISSUE THREAD

**Issue by PAEz** [und3fined/medium-unlocker#4]
You might be more knowledgeable on this stuff, so....

Before finding this I found another manual way that works great but I cant figure how to make an extension out of it.
https://lifehacker.com/how-to-read-medium-articles-for-free-1840047253
In the comments.....
Blaine : Nick Douglas
    Go directly to t.co, the domain Twitter owns for URL shortening.
    Press F12 to open Developer Tools
    Expand "body" and the first "div"
    Click on the first "a" hyperlink, and press Enter
    Here you can type something to replace the target of the link; paste in the Medium URL
    Press Enter to save
    Click on the Twitter Bird icon on the page
    You’ll be taken to the Medium article, arriving from the t.co domain and bypassing the paywall

This works brilliantly, the reason, you can read anything AND you stay logged in so can comment and wotnot.
But so far I dont know enough to replicate this in an extension.
I tried modifying the referrer to https://t.co, but this on its own doesnt work.  Doing that and deleting the cookies makes it load, but your no longer logged in (still a nice option tho).
Anyways, yours works brilliantly as well, but thought Id mention this in case its useful later.

**Comment by und3fined** [comment]
Hi @PAEz,

Currently referrer from Twitter not work. My solution patch to cookie, it's will bypass paywall, no more way for read free medium content

**Comment by PAEz** [comment]
Ummm like I said, worked for me.  Maybe I wasnt trying on the right site.....
https://betterprogramming.pub/observer-design-pattern-in-javascript-c839ee49add4
...thats the one I couldnt read without the help of your extension or the twitter stuff I mentioned above...either allowed me to read the article.

**Comment by und3fined** [comment]
Referrer from twitter work to June 2021, the next time Medium use graphql for get content and t.co nerver work again.
