### ISSUE TITLE
Paywall stands still on medium sub "geekculture"

### ISSUE THREAD

**Issue by balovp** [und3fined/medium-unlocker#43]
Paywall stands still on medium sub "geekculture"

https://medium.com/geekculture/6-different-types-of-slowly-changing-dimensions-and-how-to-apply-them-b152ef908d4e

**Comment by und3fined** [comment]
@balovp are u sure?

![Screenshot 2023-05-03 at 14-19-17 6 Different Types of Slowly Changing Dimensions and How to Apply Them](https://user-images.githubusercontent.com/2163878/235853868-05530352-1d7b-4505-945a-3c8f8464f618.png)

**Comment by balovp** [comment]
@und3fined yeah, it works, thanks. Made some testing on conflicts with other extensions. It seems, that when DuckDuckGo Privacy Essentials extention is on, the Medium Unlocker does not work.
