### ISSUE TITLE
Unlocker not working anymore?

### ISSUE THREAD

**Issue by D-Rekk** [und3fined/medium-unlocker#47]
I'm getting the "upgrade" button to an article([this](https://medium.com/workings/true-transclusion-in-obsidian-6d2e05235bd)). Maybe Medium has updated its code?

<img width="1009" alt="Screenshot 2023-07-12 alle 22 13 43" src="https://github.com/und3fined/medium-unlocker/assets/46907875/f8e87970-6a6a-4d74-9a3f-e7fa1a23fb13">

**Comment by mozayed007** [comment]
it's because of the manifest deprication, Manifest version 2 is deprecated. The error will appear when you go to manage extensions the error appears on the extension :"D

**Comment by und3fined** [comment]
@D-Rekk I check and have a problem with **Member-only** post.
Now, Medium not allow guest view full thread...

This a BAD NEWS. I will double-check more carefully when I have free time.

**Comment by hswmartin** [comment]
> it's because of the manifest deprication, Manifest version 2 is deprecated. The error will appear when you go to manage extensions the error appears on the extension :"D

I don't think this is  the real reason.

**Comment by und3fined** [comment]
BAD NEWS :(

I checked again and currently there is no way to bypass the paywall.
