### ISSUE TITLE
Please support Safari

### ISSUE THREAD

**Issue by Abinthur** [und3fined/medium-unlocker#5]
Hi, I am a solid fan of Medium Unlocker, excellent work! But would you please consider make this extension available on Safari? Either of the following two ways should be fine.

1. Use Xcode to transfer to [Safari extension](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari).
Demerits: Maybe more strict rules enacted by Apple.
2. Some how make it a [Tampermonkey script](https://www.tampermonkey.net/?ext=dhdg&browser=safari)(which can be used in Safari).
Demerits: May lack ideal pricing methods.

Safari has a great potential and thanks in advance!

**Comment by und3fined** [comment]
@Abinthur the extension use webRequestBlocking, it's not support by Apple Safari. I need make a macOS app for this case. Currently, i can't make it

<img width="593" alt="Screen Shot 2022-01-27 at 14 53 52" src="https://user-images.githubusercontent.com/2163878/151315080-34f22c78-7923-45dc-a9da-dd09253f463f.png">

**Comment by pawanjenu** [comment]
Don’t we have any alternative to webrequestblocking?

**Comment by und3fined** [comment]
> Don’t we have any alternative to webrequestblocking?

Yes, no more alternative for safari. It's require a thirdparty application to handle request and patch it.

**Comment by pawanjenu** [comment]
> > Don’t we have any alternative to webrequestblocking?
> 
> @pawanjenu Yes, no more alternative for safari. It's require a thirdparty application to handle request and patch it.

let's build one? am ready to contribute? what say?

**Comment by und3fined** [comment]
> > > Don’t we have any alternative to webrequestblocking?
> 
> > 
> 
> > @pawanjenu Yes, no more alternative for safari. It's require a thirdparty application to handle request and patch it.
> 
> 
> 
> let's build one? am ready to contribute? what say?

I welcome for any contribute, you can make macOS application?

**Comment by pawanjenu** [comment]
> > > > Don’t we have any alternative to webrequestblocking?
> > 
> > 
> > > 
> > 
> > 
> > > @pawanjenu Yes, no more alternative for safari. It's require a thirdparty application to handle request and patch it.
> > 
> > 
> > let's build one? am ready to contribute? what say?
> 
> I welcome for any contribute, you can make macOS application?

not particularly, but I have experience building applications.

**Comment by und3fined** [comment]
@pawanjenu Currently, I'm waiting for the new MBP. After received it i'll start in free time.

**Comment by Abinthur** [comment]
Hi, I have downloaded Xcode on Mac and tried to [transfer](https://www.youtube.com/watch?v=9h6OQ5IGmKI&t=3s).
For personal usage(without developer ID and your consent),  I ends up here with some bugs(Sadly):
![IMG_1203](https://user-images.githubusercontent.com/62495250/153714494-ec978be0-25fc-4521-abdd-7ff4dfd2ed25.jpg)

I went through the demo by [Apple ](https://developer.apple.com/videos/play/wwdc2021/10104/)and found why:
It seems `webquest` are not allowed for [Safari entensions](https://developer.apple.com/videos/play/wwdc2021/10027). Maybe some significant code changes should be made.
![IMG_1199](https://user-images.githubusercontent.com/62495250/153714497-4534644c-2c15-4d3e-8aff-d704aaa59be5.PNG)
![IMG_1200](https://user-images.githubusercontent.com/62495250/153714499-da4300a8-5058-4368-910f-0c7813ab7208.PNG)

**Comment by und3fined** [comment]
@Abinthur webRequest in Safari is limited, you need passthough request to third-party app (macOS app) and change it. No more way for Safari

**Comment by pawanjenu** [comment]
> @pawanjenu Currently, I'm waiting for the new MBP. After received it i'll start in free time.

any ETA when that will be released?

**Comment by und3fined** [comment]
> > @pawanjenu Currently, I'm waiting for the new MBP. After received it i'll start in free time.
> 
> any ETA when that will be released?

:D MBP in country not have a ETA, I waiting in 8 weeks but no ship

**Comment by pawanjenu** [comment]
any updates?

**Comment by und3fined** [comment]
> any updates?

I'm here,
I have a problem with modified `header` request on safari. It's not allowed. But i have a idea use other browser for scraper content and replace to Safari

i have a question. How many browsers do you use on device?

**Comment by pawanjenu** [comment]
in my IOS, I use firefox, chrome, safari.

**Comment by pawanjenu** [comment]
> I'm here, I have a problem with modified `header` request on safari. It's not allowed. But i have a idea use other browser for scraper content and replace to Safari

if we build a app of some sort, that wont be able to do it?

**Comment by und3fined** [comment]
> if we build a app of some sort, that wont be able to do it?

@pawanjenu Currently, I can make it work, but can't login to Medium.

**Comment by pawanjenu** [comment]
> > if we build a app of some sort, that wont be able to do it?
> 
> @pawanjenu Currently, I can make it work, but can't login to Medium.

we can start with that, 
and work on how to get the login working?

**Comment by pawanjenu** [comment]
@und3fined ??

**Comment by und3fined** [comment]
> @und3fined ??

@pawanjenu It's was a bad experience, i do not want that.

Pls wait to WWDC 2022, maybe new api change. Then I will start the project

**Comment by und3fined** [comment]
@pawanjenu I have a question. Your Medium data will though via proxy. What do you think about this?

**Comment by pawanjenu** [comment]
I don't see any issue with my medium data going via a proxy TBH.

**Comment by und3fined** [comment]
@pawanjenu i have one more quest.
I'll release a paid version for macOS, it's work with any browser, can u pay it?

**Comment by pawanjenu** [comment]
If it works, then am willing too.

**Comment by pawanjenu** [comment]
any updates?

**Comment by und3fined** [comment]
> any updates?

I don't have free time

**Comment by pawanjenu** [comment]
@und3fined , still the same?
