### ISSUE TITLE
not working for https://medium.com/@anthonydmays/how-to-practice-leetcode-questions-the-right-way-4f9735cf06c6

### ISSUE THREAD

**Issue by HimagnyaP** [und3fined/medium-unlocker#57]
![image](https://github.com/und3fined/medium-unlocker/assets/113088922/2b5e008e-1070-4f7e-872e-87dbb825bb4c)

**Comment by tinyc0der** [comment]
try this
https://webcache.googleusercontent.com/search?q=cache:https://medium.com/@anthonydmays/how-to-practice-leetcode-questions-the-right-way-4f9735cf06c6&strip=0&vwsrc=1&referer=medium-parser
