### ISSUE TITLE
Adding new sites to the list

### ISSUE THREAD

**Issue by WINOFFRG** [und3fined/medium-unlocker#6]
Can we give the option to add new site in the list form UI itself? Maybe we can show the option when clicked on extension to add this site to whitelist and then it adds it to the file.

**Comment by und3fined** [comment]
@WINOFFRG Added new domain, need rebuild extension and upload to Store. I will try to finish it in near future.

**Comment by rubiin** [comment]
This looks like a nice feature any ETA
